package org.atm.presentation.views.login;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.awt.*;

public class LoginView extends JFrame
{
    private final LoginController controller;

    private JPanel panels,panel;
    private JTextField userfield;
    private JPasswordField passwordfield; 
    private JButton btstart;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public LoginView() 
    
    {
        this.setTitle("start form");
        this.setSize(420, 380);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLayout(new BorderLayout());
        this.setContentPane(this.panels);
        this.pack();
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        this.controller = new LoginController(this);
    }
      
    
    private void $$$setupUI$$$() 
    {
        Color customColor = new Color(0, 139, 139);
        getContentPane().setBackground(customColor);

        panels = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 10));
        panels.setBackground(new Color(24, 26, 42));

        JLabel titleLabel = new JLabel("Start Sesión");
        titleLabel.setBounds(120, 20, 200, 30);
        titleLabel.setFont(new Font("Open Sans", Font.BOLD, 30)); // Usar fuente personalizada
        titleLabel.setForeground(Color.LIGHT_GRAY);
        panels.add(titleLabel);
        add(panels, BorderLayout.NORTH);

        JPanel panel = new JPanel();
        panel.setBackground(new Color(24, 26, 42));
        panel.setLayout(null); // Usar layout nulo para mayor control sobre la ubicación de los componentes

        JLabel userLabel = new JLabel("User");
        userLabel.setBounds(50, 40, 150, 25);
        userLabel.setFont(new Font("Open Sans", Font.BOLD, 20));
        userLabel.setForeground(Color.LIGHT_GRAY);
        panel.add(userLabel);

        userfield = new JTextField(20);
        userfield.setBounds(180, 40, 160, 25); // Ajustar posición
        userfield.setFont(new Font("Open Sans", Font.BOLD, 18));
        userfield.setBackground(new Color(36, 38, 54)); // Color de los campos
        userfield.setBorder(BorderFactory.createLineBorder(new Color(255, 82, 82))); // Borde color rojo
        userfield.setForeground(Color.white);
        panel.add(userfield);

        JLabel passwordLabel = new JLabel("PIN");
        passwordLabel.setBounds(65, 120, 150, 25);
        passwordLabel.setFont(new Font("Open Sans", Font.BOLD, 20)); 
        passwordLabel.setForeground(Color.LIGHT_GRAY);
        panel.add(passwordLabel);

        passwordfield = new JPasswordField(20);
        passwordfield.setBounds(180, 120, 160, 25);
        passwordfield.setFont(new Font("Open Sans", Font.BOLD, 20));
        passwordfield.setBackground(new Color(36, 38, 54)); // Color de los campos
        passwordfield.setBorder(BorderFactory.createLineBorder(new Color(255, 82, 82))); // Borde color rojo
        passwordfield.setForeground(Color.white);
        panel.add(passwordfield);

        btstart = new JButton("Start");
        btstart.setBounds(115, 180, 160, 40);
        btstart.setFont(new Font("Open Sans", Font.BOLD, 20));
        btstart.setForeground(Color.WHITE);
        btstart.setBackground(new Color(119, 136, 153));
        panel.add(btstart);

        
        add(panel, BorderLayout.CENTER);
    }
    
    public JComponent $$$getRootComponent$$$() 
    {
        return panels;
    }

    public JTextField getUserField() {
        return userfield;
    }

    public JPasswordField getPasswordField() {
        return passwordfield;
    }

    public JButton getLoginButton() {
        return btstart;
    }

}
